name = "ahlan-homestays"
main = ".open-next/worker.js"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "AhlanDB"
database_id = "REPLACE_WITH_YOUR_D1_ID"