name = "ahlan"
main = ".open-next/worker.js"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "AhlanDB"
database_id = "2ef220e5-7853-4494-946d-8f59070ad6cf"