-- Ahlan Homestays D1 Seed Data (FREE Tier Optimized)

DELETE FROM rooms;
INSERT INTO rooms (id, name, size, guests, basePrice, image, desc, features, tag, tagColor, availability) VALUES 
('deluxe-forest', 'Deluxe Forest View Room', '300+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/forest-view.png', 'Wake up to lush tropical forest greenery. Spacious deluxe room with premium furnishings and serene nature views.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Forest Views', 'bg-palm', 'Only 1 Available'),
('deluxe-premium', 'Deluxe Premium Stay Room', '300+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/premium-stay.png', 'Elevated comfort with higher floor views and upgraded amenities. Perfect for couples seeking a touch of extra luxury.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Most Popular', 'bg-champagne', 'Only 1 Available'),
('deluxe-family', 'Deluxe Family Comfort Room', '350+ sq ft', 'Max 4 Guests', 2500, '/images/rooms/family-comfort.png', 'Generously sized for families. Extra bedding options, separate seating area, and child-friendly setup.', '["Multiple Beds","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Family Favourite', 'bg-ocean-light', 'Only 1 Available'),
('deluxe-couple', 'Deluxe Couple Retreat Room', '300+ sq ft', 'Max 2 Guests', 2500, '/images/rooms/couple-retreat.png', 'Romantic premium setup with optional rose petal décor, private balcony access, and personalized turndown service.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Rose Décor Option"]', 'Romantic', 'bg-rose-500', 'Only 1 Available'),
('deluxe-runway', 'Deluxe Runway View Room', '320+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/runway-view.png', 'Perfect for aviation enthusiasts. Watch planes land and take off from the comfort of your luxury premium room.', '["King-Size Bed","AC","Soundproof Windows","Smart TV","Free WiFi","Premium Bath"]', 'Unique View', 'bg-blue-600', 'Only 1 Available');

DELETE FROM packages;
INSERT INTO packages (id, title, duration, basePrice, priceSuffix, image, badge, badgeColor, desc, destinations, inclusions, itinerary) VALUES 
('p1', 'Romantic Honeymoon Escape', '4 Nights / 5 Days', 29999, '/couple', '/images/packages/romantic-honeymoon.png', 'Couple Favourite', 'bg-rose-500', 'A magical romantic getaway featuring private beach dinners, photoshoots, and sunset cruises.', '["Port Blair","Havelock Island","Neil Island"]', '["Deluxe Stay","All Ferry Tickets","Candlelight Dinner","Beach Photoshoot","Couples Spa","Airport Transfers"]', '[{"day":1,"title":"Arrival & Sunset Cruise","desc":"Airport pickup, check-in to Honeymoon Suite. Evening sunset cruise at Port Blair harbour."},{"day":2,"title":"Havelock Island & Radhanagar","desc":"Premium ferry to Havelock. Visit Asia''s best beach, Radhanagar. Evening candlelight dinner."},{"day":3,"title":"Elephant Beach Snorkeling","desc":"Private boat to Elephant Beach for snorkeling. Afternoon couples spa session."},{"day":4,"title":"Neil Island Romance","desc":"Ferry to Neil Island. Visit Natural Bridge and Laxmanpur beach sunset. Return to Port Blair."},{"day":5,"title":"Departure","desc":"Breakfast and airport drop with unforgettable memories."}]'),
('p2', 'Family Discovery Tour', '5 Nights / 6 Days', 18999, '/person', '/images/packages/family-discovery.png', 'Family Recommended', 'bg-palm', 'Safe, comfortable, and engaging trip designed perfectly for families with children of all ages.', '["Port Blair","Havelock Island","Ross Island"]', '["Family Suite Stay","All Ferry Tickets","Glass-Bottom Boat","Kids Activity Kit","Daily Breakfast","Airport Transfers"]', '[{"day":1,"title":"Arrival & Cellular Jail","desc":"Airport pickup. Evening visit to Cellular Jail and Light & Sound show."},{"day":2,"title":"Ross Island & North Bay","desc":"Glass bottom boat ride to see corals. Historical tour of Ross Island."},{"day":3,"title":"Havelock Island","desc":"Ferry to Havelock. Family time at Radhanagar beach."},{"day":4,"title":"Elephant Beach","desc":"Safe snorkeling and water sports for the family at Elephant Beach."},{"day":5,"title":"Return to Port Blair","desc":"Souvenir shopping and visit to Samudrika Marine Museum."},{"day":6,"title":"Departure","desc":"Airport drop."}]'),
('p3', 'Premium Island Luxury Tour', '6 Nights / 7 Days', 34556, '/person', '/images/dest_baratang.png', 'Most Popular', 'bg-champagne', 'The ultimate Andaman experience. VIP transfers, premium stays, and exclusive island tours.', '["Port Blair","Havelock","Neil","Baratang"]', '["Premium Room","Makruzz VIP Ferry","Private Cab","Scuba Diving","Limestone Caves","All Meals"]', '[{"day":1,"title":"VIP Arrival","desc":"Welcome drinks, check-in. Evening at Corbyn''s Cove beach."},{"day":2,"title":"Baratang Island","desc":"Early morning trip through Jarawa reserve to Limestone Caves."},{"day":3,"title":"Havelock Island","desc":"VIP ferry to Havelock. Sunset at Radhanagar Beach."},{"day":4,"title":"Scuba Experience","desc":"Introductory scuba diving with PADI certified instructors."},{"day":5,"title":"Neil Island","desc":"Ferry to Neil Island. Relax at Bharatpur beach."},{"day":6,"title":"Port Blair Heritage","desc":"Return to Port Blair. City tour and shopping."},{"day":7,"title":"Departure","desc":"VIP airport transfer."}]'),
('p4', 'Workation + Vacation Plan', '14 Nights / 15 Days', 45000, '/person', '/images/dest_havelock.png', 'Long Stay', 'bg-ocean-light', 'Work remotely with 100Mbps WiFi during the week, explore tropical paradise on the weekends.', '["Port Blair Base","Weekend Islands"]', '["Deluxe Room","100Mbps WiFi","Work Desk","Weekend Island Trips","Laundry","Breakfast"]', '[{"day":"Mon-Fri","title":"Remote Work Setup","desc":"High-speed WiFi, dedicated workspace, endless coffee."},{"day":"Weekends","title":"Island Hopping","desc":"Guided weekend trips to Havelock, Neil, and Ross Islands."},{"day":"Anytime","title":"Local Exploration","desc":"Evening visits to local cafes and sunset points."}]');

DELETE FROM settings;
INSERT INTO settings (key, value) VALUES 
('addonPrices', '{"Airport Pickup":800,"Airport Drop":800,"Honeymoon Decoration":1500,"Anniversary Decoration":1500,"Extra Mattress":700,"Candlelight Setup":2000,"Breakfast Upgrade":300,"Scuba Diving":3500,"Snorkeling":1000,"Parasailing":3000,"Candlelight Dinner":2500,"Photography":5000,"Private Cab":2500,"Island Guide":1000,"Music System":1000}'),
('hourlyRate', '166'),
('taxes', '0'),
('seasonalRateMultiplier', '1');