-- Ahlan Homestay D1 Seed Data (FREE Tier Optimized)

DELETE FROM rooms;
INSERT INTO rooms (id, name, size, guests, basePrice, image, desc, features, tag, tagColor, availability) VALUES 
('deluxe-forest', 'Deluxe Forest View Room', '300+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/forest-view.png', 'Wake up to lush tropical forest greenery. Spacious deluxe room with premium furnishings and serene nature views.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Forest Views', 'bg-palm', 'Only 1 Available'),
('deluxe-premium', 'Deluxe Premium Stay Room', '300+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/premium-stay.jpg', 'Elevated comfort with higher floor views and upgraded amenities. Perfect for couples seeking a touch of extra luxury.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Most Popular', 'bg-champagne', 'Only 1 Available'),
('deluxe-family', 'Deluxe Family Comfort Room', '350+ sq ft', 'Max 4 Guests', 2500, '/images/rooms/family-comfort.png', 'Generously sized for families. Extra bedding options, separate seating area, and child-friendly setup.', '["Multiple Beds","AC","Smart TV","Premium Bath","Free WiFi","Daily Cleaning"]', 'Family Favourite', 'bg-ocean-light', 'Only 1 Available'),
('deluxe-couple', 'Deluxe Couple Retreat Room', '300+ sq ft', 'Max 2 Guests', 2500, '/images/rooms/couple-retreat.jpg', 'Romantic premium setup with optional rose petal décor, private balcony access, and personalized turndown service.', '["King-Size Bed","AC","Smart TV","Premium Bath","Free WiFi","Rose Décor Option"]', 'Romantic', 'bg-rose-500', 'Only 1 Available'),
('deluxe-runway', 'Deluxe Runway View Room', '320+ sq ft', 'Max 3 Guests', 2500, '/images/rooms/runway-view.jpg', 'Perfect for aviation enthusiasts. Watch planes land and take off from the comfort of your luxury premium room.', '["King-Size Bed","AC","Soundproof Windows","Smart TV","Free WiFi","Premium Bath"]', 'Unique View', 'bg-blue-600', 'Only 1 Available');

DELETE FROM packages;
INSERT INTO packages (id, title, duration, basePrice, priceSuffix, image, badge, badgeColor, desc, destinations, inclusions, itinerary) VALUES 
('p1', 'Romantic Escape', '3 Nights / 4 Days', 0, ' (Price on Request)', '/images/packages/romantic-honeymoon.png', 'Couple Favourite', 'bg-rose-500', 'A magical romantic getaway. All itineraries include a stay at AHLAN HOMESTAYS. Add extra thrills with optional water sports like Jet Skiing, Scuba Diving, and Parasailing.', '["Port Blair","Havelock Island","Ross Island","Chidiya Tapu"]', '["Complimentary Breakfast","Sightseeing & Entry Tickets","Airport Transfers & Cab","Ferry Tickets","3-Star Accommodation","Trip Coordinator & Taxes"]', '[{"day":1,"title":"Arrival & Port Blair","desc":"Arrive at Port Blair by flight, receive a transfer to Ahlan Homestays. Afternoon: Visit Corbyn''s Cove Beach. Evening: Attend the enthralling Light and Sound show at Cellular Jail."},{"day":2,"title":"Havelock Island","desc":"Early departure by inter-island ferry to Havelock Island. Afternoon: Visit Beach No. 7 (Radha Nagar), rated as one of Asia''s most beautiful beaches. Evening: Enjoy dinner overlooking the scenic Taal Volcano."},{"day":3,"title":"Ross Island & Chidiya Tapu","desc":"Visit Ross Island (former British governing headquarters). Evening: Return to Port Blair for a city tour and a trip to Chidiya Tapu sunset point."},{"day":4,"title":"Departure","desc":"Morning airport drop-off for your journey home."}]'),
('p2', 'Adventure Explorer', '4 Nights / 5 Days', 21999, ' / person', '/images/packages/family-discovery.png', 'Adventure Pick', 'bg-blue-600', 'Thrilling island hopping and water sports adventure. Includes complimentary beachside snorkeling. Optional Jet Skiing, Scuba Diving, and more available on request.', '["Port Blair","Havelock Island","Neil Island","Ross Island"]', '["Complimentary Breakfast","Sightseeing & Entry Tickets","Airport Transfers & Cab","Ferry Tickets","3-Star Accommodation","Trip Coordinator & Taxes"]', '[{"day":1,"title":"Arrival & Cellular Jail","desc":"Arrive in Port Blair, transfer to Ahlan Homestays. Visit Corbyn''s Cove Beach in the afternoon, and attend the Light and Sound show at Cellular Jail in the evening."},{"day":2,"title":"Havelock Island","desc":"Early morning ferry to Havelock Island, afternoon visit to Radha Nagar Beach, and evening dinner overlooking Taal Volcano."},{"day":3,"title":"Elephanta Beach & Neil Island","desc":"Early checkout to visit Elephanta Beach for complimentary beachside snorkeling. Return to Port Blair in the evening OR proceed from Havelock to Neil Island for an overnight stay."},{"day":4,"title":"Ross Island & Sunset","desc":"Visit Ross Island, return for a Port Blair city tour, and visit Chidiya Tapu for the sunset. Stay in Port Blair."},{"day":5,"title":"Departure","desc":"Transfer to the airport for departure."}]'),
('p3', 'Family Fun', '5 Nights / 6 Days', 25555, ' / person', 'https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&q=80&w=800', 'Family Recommended', 'bg-palm', 'Safe, comfortable, and engaging trip designed perfectly for families with children of all ages. Enjoy the best of Andaman''s beaches and history.', '["Port Blair","Havelock","Neil Island","Ross Island"]', '["Complimentary Breakfast","Sightseeing & Entry Tickets","Airport Transfers & Cab","Ferry Tickets","3-Star Accommodation","Trip Coordinator & Taxes"]', '[{"day":1,"title":"Arrival & Port Blair","desc":"Arrive in Port Blair, transfer to Ahlan Homestays. Visit Corbyn''s Cove Beach in the afternoon, and attend the Cellular Jail Light and Sound show in the evening."},{"day":2,"title":"Havelock Island","desc":"Early morning ferry to Havelock Island, afternoon visit to Radha Nagar Beach, and evening dinner overlooking Taal Volcano."},{"day":3,"title":"Elephanta & Neil Island","desc":"Early checkout for Elephanta Beach (complimentary snorkeling). In the afternoon, travel to Neil Island and stay overnight at a resort."},{"day":4,"title":"Neil Island & Return","desc":"Visit Laxmanpur Beach at Neil Island for a photography spot. Return to Port Blair via Nautika/Makruzz ferry. Evening visit to Chidiya Tapu for the sunset."},{"day":5,"title":"City Tour","desc":"After breakfast, embark on a Port Blair city tour. After lunch, visit Chidiya Tapu sunset point or Ross Island and North Bay Island."},{"day":6,"title":"Departure","desc":"Transfer to the airport for departure."}]');

DELETE FROM settings;
INSERT INTO settings (key, value) VALUES 
('addonPrices', '{"Airport Pickup":800,"Airport Drop":800,"Honeymoon Decoration":1500,"Anniversary Decoration":1500,"Extra Mattress":700,"Candlelight Setup":2000,"Breakfast Upgrade":300,"Scuba Diving":3500,"Snorkeling":1000,"Parasailing":3000,"Candlelight Dinner":2500,"Photography":5000,"Private Cab":2500,"Island Guide":1000,"Music System":1000}'),
('hourlyRate', '166'),
('taxes', '0'),
('seasonalRateMultiplier', '1');